spring:
  profiles:
    active: local
  application:
    name: food-sharing-service

app:
  food-sharing-service:
    datasource:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/ern
      username: postgres
      password: a206
      schema: fs
      maximumPoolSize: 10