-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2021-11-07 14:26:14 YEKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

drop schema fs cascade;
create schema fs;


set search_path to fs;

CREATE TABLE act_produce (
    id           INTEGER NOT NULL,
    date_create  DATE NOT NULL
);

COMMENT ON TABLE act_produce IS
    'Акт передачи от производителя';

COMMENT ON COLUMN act_produce.id IS
    'ID';

COMMENT ON COLUMN act_produce.date_create IS
    'Дата создания';

ALTER TABLE act_produce ADD CONSTRAINT act_produce_pk PRIMARY KEY ( id );

CREATE TABLE act_receiver (
    id           INTEGER NOT NULL,
    date_create  DATE NOT NULL,
    receiver_id  INTEGER NOT NULL
);

COMMENT ON TABLE act_receiver IS
    'Акт при передаче получателю';

COMMENT ON COLUMN act_receiver.id IS
    'ID';

COMMENT ON COLUMN act_receiver.date_create IS
    'Дата создания';

COMMENT ON COLUMN act_receiver.receiver_id IS
    'ID получателя';

ALTER TABLE act_receiver ADD CONSTRAINT act_receiver_pk PRIMARY KEY ( id );

CREATE TABLE city (
    id    INTEGER NOT NULL,
    name  VARCHAR(100) NOT NULL
);

COMMENT ON TABLE city IS
    'Город';

COMMENT ON COLUMN city.id IS
    'ID';

COMMENT ON COLUMN city.name IS
    'Название';

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( id );

CREATE TABLE producer (
    id             INTEGER NOT NULL,
    name           VARCHAR(300) NOT NULL,
    city_id        INTEGER NOT NULL,
    date_register  DATE NOT NULL,
    addres         VARCHAR(300)
);

COMMENT ON TABLE producer IS
    'Производитель';

COMMENT ON COLUMN producer.id IS
    'ID';

COMMENT ON COLUMN producer.name IS
    'Название';

COMMENT ON COLUMN producer.city_id IS
    'Город ID';

COMMENT ON COLUMN producer.date_register IS
    'Дата регистрации';

COMMENT ON COLUMN producer.addres IS
    'Адрес';

ALTER TABLE producer ADD CONSTRAINT producer_pk PRIMARY KEY ( id );

CREATE TABLE product_item (
    id     INTEGER NOT NULL,
    name   VARCHAR(300),
    count  NUMERIC,
    mass   NUMERIC
);

COMMENT ON TABLE product_item IS
    'Элемент продуктового набора';

COMMENT ON COLUMN product_item.id IS
    'ID';

COMMENT ON COLUMN product_item.count IS
    'Количество';

COMMENT ON COLUMN product_item.mass IS
    'Масса, кг';

ALTER TABLE product_item ADD CONSTRAINT product_item_pk PRIMARY KEY ( id );

CREATE TABLE product_set (
    id               INTEGER NOT NULL,
    date_produce     DATE NOT NULL,
    mass             NUMERIC,
    producer_id      INTEGER NOT NULL,
    product_item_id  INTEGER NOT NULL,
    volunteer_count  INTEGER,
    act_produce_id   INTEGER NOT NULL,
    act_receiver_id  INTEGER NOT NULL
);

COMMENT ON TABLE product_set IS
    'Набор продуктов';

COMMENT ON COLUMN product_set.id IS
    'ID';

COMMENT ON COLUMN product_set.date_produce IS
    'Дата производства набора';

COMMENT ON COLUMN product_set.mass IS
    'Масса, кг.';

COMMENT ON COLUMN product_set.volunteer_count IS
    'Сколько волонтёров требуется для распространения набора';

ALTER TABLE product_set ADD CONSTRAINT product_set_pk PRIMARY KEY ( id );

CREATE TABLE product_set_history (
    id                     INTEGER NOT NULL,
    product_set_id         INTEGER NOT NULL,
    product_set_status_id  INTEGER NOT NULL,
    date_status            DATE NOT NULL
);

COMMENT ON TABLE product_set_history IS
    'История набора подуктов';

COMMENT ON COLUMN product_set_history.id IS
    'ID';

COMMENT ON COLUMN product_set_history.product_set_id IS
    'ID Продуктового набора';

COMMENT ON COLUMN product_set_history.product_set_status_id IS
    'ID Статуса';

COMMENT ON COLUMN product_set_history.date_status IS
    'Дата смены статуса';

ALTER TABLE product_set_history ADD CONSTRAINT product_set_history_pk PRIMARY KEY ( id );

CREATE TABLE product_set_status (
    id    INTEGER NOT NULL,
    name  VARCHAR(100) NOT NULL
);

COMMENT ON TABLE product_set_status IS
    'Статус набора продуктов';

COMMENT ON COLUMN product_set_status.id IS
    'ID';

COMMENT ON COLUMN product_set_status.name IS
    'Наименование';

ALTER TABLE product_set_status ADD CONSTRAINT product_set_status_pk PRIMARY KEY ( id );

CREATE TABLE product_set_volunteer (
    id              INTEGER NOT NULL,
    product_set_id  INTEGER NOT NULL,
    volunteer_id    INTEGER NOT NULL
);

COMMENT ON TABLE product_set_volunteer IS
    'Связь продуктового набора с волонтёрами';

COMMENT ON COLUMN product_set_volunteer.id IS
    'ID';

ALTER TABLE product_set_volunteer ADD CONSTRAINT product_set_volunteer_pk PRIMARY KEY ( id );

CREATE TABLE receiver (
    id                INTEGER NOT NULL,
    name              VARCHAR(300) NOT NULL,
    address           VARCHAR(300) NOT NULL,
    city_id           INTEGER NOT NULL,
    receiver_type_id  INTEGER NOT NULL
);

COMMENT ON TABLE receiver IS
    'Получатель';

COMMENT ON COLUMN receiver.id IS
    'ID';

COMMENT ON COLUMN receiver.name IS
    'Название, имя';

COMMENT ON COLUMN receiver.address IS
    'Адрес';

ALTER TABLE receiver ADD CONSTRAINT receiver_pk PRIMARY KEY ( id );

CREATE TABLE receiver_type (
    id    INTEGER NOT NULL,
    name  VARCHAR(300) NOT NULL
);

COMMENT ON TABLE receiver_type IS
    'Тип получателя';

COMMENT ON COLUMN receiver_type.id IS
    'ID';

COMMENT ON COLUMN receiver_type.name IS
    'Наименование';

ALTER TABLE receiver_type ADD CONSTRAINT receiver_type_pk PRIMARY KEY ( id );

CREATE TABLE schedule_status (
    id    INTEGER NOT NULL,
    name  VARCHAR(100) NOT NULL
);

COMMENT ON TABLE schedule_status IS
    'Статус расписания';

COMMENT ON COLUMN schedule_status.id IS
    'ID';

COMMENT ON COLUMN schedule_status.name IS
    'Наименование';

ALTER TABLE schedule_status ADD CONSTRAINT schedule_status_pk PRIMARY KEY ( id );

CREATE TABLE scheduler (
    id                  INTEGER NOT NULL,
    product_set_id      INTEGER NOT NULL,
    date_produce        DATE NOT NULL,
    schedule_status_id  INTEGER NOT NULL
);

COMMENT ON TABLE scheduler IS
    'Расписание необходимости забора продуктов';

COMMENT ON COLUMN scheduler.id IS
    'ID';

COMMENT ON COLUMN scheduler.date_produce IS
    'Дата предоставления продуктов производителем';

ALTER TABLE scheduler ADD CONSTRAINT scheduler_pk PRIMARY KEY ( id );

CREATE TABLE volunteer (
    id             INTEGER NOT NULL,
    name           VARCHAR(300) NOT NULL,
    date_register  DATE NOT NULL,
    is_curator     INTEGER NOT NULL,
    is_admin       INTEGER NOT NULL,
    id2            INTEGER NOT NULL
);

COMMENT ON TABLE volunteer IS
    'Волонтёр';

COMMENT ON COLUMN volunteer.id IS
    'ID';

COMMENT ON COLUMN volunteer.name IS
    'Имя';

COMMENT ON COLUMN volunteer.date_register IS
    'Дата регистрации';

COMMENT ON COLUMN volunteer.is_curator IS
    'Признак куратора';

COMMENT ON COLUMN volunteer.is_admin IS
    'Признак администратора';

ALTER TABLE volunteer ADD CONSTRAINT volunteer_pk PRIMARY KEY ( id );

ALTER TABLE act_receiver
    ADD CONSTRAINT act_receiver_receiver_fk FOREIGN KEY ( receiver_id )
        REFERENCES receiver ( id );

ALTER TABLE producer
    ADD CONSTRAINT producer_city_fk FOREIGN KEY ( city_id )
        REFERENCES city ( id );

ALTER TABLE product_set
    ADD CONSTRAINT product_set_act_produce_fk FOREIGN KEY ( act_produce_id )
        REFERENCES act_produce ( id );

ALTER TABLE product_set
    ADD CONSTRAINT product_set_act_receiver_fk FOREIGN KEY ( act_receiver_id )
        REFERENCES act_receiver ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE product_set_history
    ADD CONSTRAINT prod_set_hist_prod_set_fk FOREIGN KEY ( product_set_id )
        REFERENCES product_set ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE product_set_history
    ADD CONSTRAINT prod_set_hist_prod_set_status_fk FOREIGN KEY ( product_set_status_id )
        REFERENCES product_set_status ( id );

ALTER TABLE product_set
    ADD CONSTRAINT product_set_producer_fk FOREIGN KEY ( producer_id )
        REFERENCES producer ( id );

ALTER TABLE product_set
    ADD CONSTRAINT product_set_product_item_fk FOREIGN KEY ( product_item_id )
        REFERENCES product_item ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE product_set_volunteer
    ADD CONSTRAINT prod_set_volunt_prod_set_fk FOREIGN KEY ( product_set_id )
        REFERENCES product_set ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE product_set_volunteer
    ADD CONSTRAINT prod_set_volunt_volunt_fk FOREIGN KEY ( volunteer_id )
        REFERENCES volunteer ( id );

ALTER TABLE receiver
    ADD CONSTRAINT receiver_city_fk FOREIGN KEY ( city_id )
        REFERENCES city ( id );

ALTER TABLE receiver
    ADD CONSTRAINT receiver_receiver_type_fk FOREIGN KEY ( receiver_type_id )
        REFERENCES receiver_type ( id );

ALTER TABLE scheduler
    ADD CONSTRAINT scheduler_product_set_fk FOREIGN KEY ( product_set_id )
        REFERENCES product_set ( id );

ALTER TABLE scheduler
    ADD CONSTRAINT scheduler_schedule_status_fk FOREIGN KEY ( schedule_status_id )
        REFERENCES schedule_status ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   4
-- WARNINGS                                 0
